---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup/install tasks.
- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: setup-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- import_tasks: setup-OpenBSD.yml
  when: ansible_os_family == 'OpenBSD'

- import_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

# Vhost configuration.
- import_tasks: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

# added by Lisa Hu
- name: delete /etc/nginx/sites-enabled/default
  file: path="/etc/nginx/sites-enabled/default" state=absent
  notify:
    - reload nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
