version: 0.0
os: linux
files:
  - source: test
    destination: /lisacodedeploy2/test
permissions:
  - object: /lisacodedeploy2/test
    pattern: "*.*"
    mode: 777
    type:
      - file
hooks:
  AfterInstall:
    - location: test/run_test.sh
      timeout: 300
