version: 0.0
os: linux
files:
  - source: /
    destination: /lisacodedeploy2/
permissions:
  - object: /lisacodedeploy2/test
    pattern: "*.*"
    mode: 755
    type:
      - file
hooks:
    BeforeInstall:
    - location: test/run_test.sh
    - timeout: 3600
    AfterInstall:
    - location: test/run_test.sh
    - timeout: 3600
