---
- name: systemctl enable airflow-webserver.service airflow-scheduler.service,airflow-flower.service
  become_user: root
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
  - 'airflow-webserver'
  - 'airflow-scheduler'
  - 'airflow-flower'
