---
- name: install airflow[s3, celery, flower]
  become_user: root
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - airflow
    - s3
    - celery
    - flower #TBD
- name:
  command: airflow initdb
- name: Clean artifact path
  file:
    state: absent
    path: "{{ remote_home }}/airflow/airflow.db"
