---
- name: Update and upgrade apt.
  become_user: root
  apt: update_cache=yes upgrade=dist cache_valid_time=1 force=yes
- name: I have to run this so that python --version shows python 3.5 not python2.
  become_user: root
  command: update-alternatives --install /usr/bin/python python /usr/bin/python3.5 1 #TBD: should I make sure it run only once?
- name: Install python3-pip
  become_user: root
  apt: name=python3-pip state=installed
- name: Upgrade pip so that pip becomes 9.0.1
  pip:
    name: pip
    extra_args: --upgrade
- name: I run this so that pip --version shows 9.0.1 not 8.X.X.
  become_user: root
  command: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1 #TBD: should I make sure it run only once?
- name: test pip --version
  shell: pip --version
  register: hello
- debug: msg="{{ hello.stdout }}"
- name: test python --version
  shell: python --version
  register: hello
- debug: msg="{{ hello.stdout }}"
