---
- name: Install unixodbc-dev
  become_user: root
  apt: name=unixodbc-dev state=installed
- name: install pyodbc, pandas, boto3, awscli, flask-bcrypt using pip
  become_user: root
  pip:
    name: "{{ item }}"
    state: present
  with_items:
  - pyodbc
  - psycopg2
  - pandas
  - boto3
  - awscli
  - flask-bcrypt
