---
- name: Install unixodbc-dev
  become_user: root
  apt: name=unixodbc-dev state=installed
- name: install pyodbc, pandas, boto3, awscli, flask-bcrypt using pip
  become_user: root
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
    - { name: pyodbc, version: 4.0.17 }
    - { name: psycopg2, version: 2.7.3.1 }
    - { name: pandas, version: 0.20.3 }
    - { name: boto3, version: 1.4.7 }
    - { name: awscli, version: 1.11.168 }
    - { name: flask-bcrypt, version: 0.7.1 }
