pipeline {
  agent any

  stages {
    stage('build') {
      steps {
        echo 'this is build stage, nothing to build for python'
      }
    }

    stage('test') {
      steps {
        echo 'this is test stage'
        src/integration_test.py
      }
    }

    stage('deploy') {
      steps {
        echo 'this deploy stage'
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'de/jenkins-test/src/*', fingerprint: true
    }
  }

}
