---
- hosts: master:workers
  become: yes
  remote_user: ubuntu
  tasks:
  - name: Set authorized key from file
    authorized_key:
      user: "{{ user }}" #e.g. etluser
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
