---
- name: check out git repository de-datapipeline.git
  git:
    repo: git@gitlab.feicore.io:DataEngineering/de-datapipeline.git
    dest: "{{ git_checkout_dir }}"
    update: yes
    version: "{{ git_commit_version }}"
  tags: gitlab
- name: check out git repository de-biscripts.git
  git:
    repo: git@gitlab.feicore.io:DataEngineering/de-biscripts.git
    dest: "{{ git_checkout_dir_biscripts }}"
    update: yes
    version: "{{ git_commit_version_biscripts }}"
  tags: gitlab
